/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 3dac5aaec817f646ba235318783a5160)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "DeviceAgent";
	}
	interface Env {
		DeviceAgent: DurableObjectNamespace<import("./src/server").DeviceAgent>;
	}
}
interface Env extends Cloudflare.Env {}
