[env:adafruit_feather_esp32s2]
platform = espressif32@6.12.0
board = adafruit_feather_esp32s2
framework = arduino
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_ldf_mode = deep
lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.0
    adafruit/Adafruit LC709203F@^1.3.4
